### ISSUE TITLE
Bootstrap service locked up

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-templates#52]
For some reason the bootstrap service got locked up in trying to bootstrap a certain node.

This node fails to mount_and_partition disks, with error message "Could not find eligible disks."

![afbeelding](https://user-images.githubusercontent.com/15246294/37699288-3335f5f8-2ce7-11e8-8e32-6d08924993d7.png)

**Comment by FastGeert** [comment]
I think we'll need to add some timeouts somewhere.

**Comment by serboctor** [comment]
"Could not find eligible disks" usually happens when sal can't find a disk to be used for the fscache, it should have nothing to do with `mount_and_partition` and it happens before it reaches `mount_and_partition` call. @FastGeert said he will let me know if it happens again and try to get me a fuller stacktrace.

**Comment by zaibon** [comment]
this service is not used anymore, so I'll close this issue
